version: "3.7"

volumes:
  postgres:
    driver: local
  ipfs_staging:
    driver: local
  ipfs_data:
    driver: local

services:
  postgres:
    image: "postgres:12"
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./scripts/postgres/1-create-database.sql:/docker-entrypoint-initdb.d/1-create-database.sql
    ports:
      - 5432:5432
  ipfs:
    image: ipfs/go-ipfs
    command:
      - daemon
      - "--enable-pubsub-experiment"
    volumes:
      - ipfs_staging:/export
      - ipfs_data:/data/ipfs
    ports:
      - 4001:4001
      - 8080:8080
      - 5001:5001
  ganache:
    image: trufflesuite/ganache-cli
    ports:
      - 8545:8545
    entrypoint:
      - node
      - /app/ganache-core.docker.cli.js
      - --deterministic
      - --mnemonic
      - 'enemy boat gauge orphan column panel prepare cave only first limb garlic'
