name: Main
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: '14'
      - name: Setup Python
        uses: actions/setup-python@v2
      - name: Setup PNPM
        uses: pnpm/action-setup@v1.2.0
        with:
          version: 5.8.0
          run_install: |
            - args: [--frozen-lockfile]
      - name: Build
        run: pnpm run build
